# Generated by Django 4.2.5 on 2024-03-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='AdventurePackage',
            fields=[
                ('adventure_id', models.AutoField(primary_key=True, serialize=False)),
                ('locations', models.CharField(max_length=255)),
                ('no_of_activities', models.IntegerField(default=1)),
                ('no_of_places', models.IntegerField(default=1)),
                ('cost', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.admin')),
            ],
            options={
                'db_table': 'AdventurePackage',
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('package_name', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('no_of_passengers', models.IntegerField(default=1)),
                ('total_cost', models.CharField(max_length=100)),
                ('cost_per_person', models.CharField(max_length=100)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.adventurepackage')),
            ],
            options={
                'db_table': 'BookingDetail',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user')),
            ],
            options={
                'db_table': 'User Feedback',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('locations', models.CharField(max_length=255)),
                ('no_of_passengers', models.IntegerField(default=1)),
                ('total_cost', models.CharField(default=0, max_length=100)),
                ('cost_per_person', models.CharField(default=0, max_length=100)),
                ('start_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.bookingdetail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user')),
            ],
            options={
                'db_table': 'Travels',
            },
        ),
        migrations.CreateModel(
            name='TopDestinations',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_names', models.CharField(max_length=255)),
                ('no_of_places', models.IntegerField(default=1)),
                ('no_of_activities', models.IntegerField(default=1)),
                ('price', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.admin')),
            ],
            options={
                'db_table': 'Top_Destinations',
            },
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user'),
        ),
    ]
