# Generated by Django 4.2.7 on 2024-02-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurePackage',
            fields=[
                ('adventure_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activities', models.TextField()),
                ('images', models.ImageField(upload_to='adventure_package_images/')),
            ],
            options={
                'db_table': 'AdventurePackage',
            },
        ),
        migrations.CreateModel(
            name='AdventurePlaceList',
            fields=[
                ('adventure_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('activities', models.TextField()),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='adventure_places/')),
            ],
            options={
                'db_table': 'AdventurePlaces',
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dates', models.DateField()),
                ('package_name', models.CharField(max_length=255)),
                ('activities', models.TextField()),
            ],
            options={
                'db_table': 'BookingDetail',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Customer Detail',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('attractions', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=45)),
                ('travel_advisory', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Destination',
            },
        ),
        migrations.CreateModel(
            name='TopDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('no_of_places', models.IntegerField()),
                ('no_of_activities', models.IntegerField()),
                ('price_amount', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Top Destinations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('first_name', models.CharField(default='Anamika', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(default='1900-01-01')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user')),
            ],
            options={
                'db_table': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenities', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('price_per_night', models.IntegerField()),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.destination')),
            ],
            options={
                'db_table': 'Travel',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.destination')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.travel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user')),
            ],
            options={
                'db_table': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.destination')),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.itinerary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbApplication.user')),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
