# Generated by Django 4.2.7 on 2024-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureplacelist',
            name='pictures',
            field=models.ImageField(upload_to='adventure_places/'),
        ),
    ]
