# Generated by Django 4.2.7 on 2024-02-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adventurepackage',
            table='AdventurePackage',
        ),
    ]
