# Generated by Django 4.2.7 on 2024-02-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0002_alter_adventurepackage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerdetail',
            table='Customer Detail',
        ),
    ]
