# Generated by Django 4.2.7 on 2024-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0003_alter_customerdetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='payment_method',
        ),
        migrations.AlterModelTable(
            name='bookingdetail',
            table='BookingDetail',
        ),
    ]
