# Generated by Django 4.2.7 on 2024-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0005_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('no_of_places', models.IntegerField()),
                ('no_of_activities', models.IntegerField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Top Destinations',
            },
        ),
    ]
