# Generated by Django 4.2.7 on 2024-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbApplication', '0007_alter_topdestination_price_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventureplacelist',
            old_name='images',
            new_name='pictures',
        ),
    ]
